# Chapter 01. Tensor Manipulation

- Vector, Matrix and Tensor
- NumPy Review
- PyTorch Tensor Allocation
- Matrix Multiplication
- Other Basic Ops

---------------------

## I. Vector, Matix and Tensor

Vector: 1D </br>
Matrix: 2D </br>
Tensor: 3D

### PyTorch Tensor Shape Convention

The shape operation is important.

#### 2D Tensor (Typical Simple Setting)
- |t| = (batch size, dim)
#### 3D Tensor (Typical Computer Vision)
- |t| = (batch size, width, height)
#### 3D Tensor (Typical Natural Language Processing - NLP)
- |t| = (batch size, length, dim)

---------------------

# II. NumPy Review

In [2]:
import numpy as np
import torch

## 1D Array with NumPy

In [5]:
t = np.array([0., 1., 2., 3., 4., 5., 6.,])
print(t)
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # Element
print('t[2:5], t[4:-1] = ', t[2:5], t[4:-1]) # Slicing
print('t[:2] t[3:] = ', t[:2], t[3:]) # Slicing

[0. 1. 2. 3. 4. 5. 6.]
Rank of t:  1
Shape of t:  (7,)
t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5], t[4:-1] =  [2. 3. 4.] [4. 5.]
t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


In [6]:
## 2D Array with Numpy

In [7]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [1., 11., 12.]])
print(t)
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [ 1. 11. 12.]]
Rank of t:  2
Shape of t:  (4, 3)


---------------------

# III. PyTorch Tensor

## 1D Array with PyTorch

In [8]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)
print(t.dim()) # rank
print(t.shape) # shape
print(t.size()) # shape
print(t[0], t[1], t[-1]) # Element
print(t[2:5], t[4:-1]) # Slicing
print(t[:2], t[3:]) # Slicing

tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


## 2D Array with PyTorch

In [12]:
t = torch.FloatTensor([[1., 2., 3.], 
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)
print(t.dim()) # rank
print(t.shape) # shape
print(t.size()) # shape
print(t[:, 1]) # get all row (:) and only second column (1)
print(t[:, 1].size()) # .size() -> get vector value
print(t[:, :-1]) # get all values except the latest coulmn

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
2
torch.Size([4, 3])
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


#### cf) about [:, :] in python
https://stackoverflow.com/questions/57872755/what-is-1-in-python
    
- [:, :]: liberally means [all rows, all coulmns]
- [:, -1]: taking all the rows and only the last column.
- [:, 1]: taking all rows but keeping the second column(1).

## Broadcasting
Automatically adjusts the size when the size of tensor is different.

</br> Because Broadcasting automatic process, finding an error is difficult. So it requires attention.

In [16]:
# Same Shape

m1 = torch.FloatTensor([[3, 3]]) # |m1| = (1, 2)
m2 = torch.FloatTensor([[2, 2]]) # |m1| == |m2|
print(m1 + m2)

tensor([[5., 5.]])


In [17]:
# Vector + Scalar
# Automatic Broadcasting

m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # 3 (scalar) -> [[3, 3]] (vector)
print(m1 + m2)

# |m1| = (1, 2)
# |m2| = (1, ) => (1, 2)
# m1 + m2 = [[1, 2] + [3, 3]]

tensor([[4., 5.]])


In [18]:
# 2 x 1 Vector + 1 x 2 Vector
# Automatic Broadcasting

m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

# |m1| = (1, 2) => (2, 2)
# |m2| = (2, 1) = > (2, 2)
# m1 + m2 = [[1, 2], [1, 2]] + [[3, 3], [4, 4]]

tensor([[4., 5.],
        [5., 6.]])


---------------------

# IV. Matrix Multiplication

## Multiplication vs Matrix Multiplication
An understanding of matrix multiplication is required.

In [21]:
print('-------')
print('Mul vs Matmul')
print('-------')
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape)
print(m1.matmul(m2))

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape)
print(m1.mul(m2))

-------
Mul vs Matmul
-------
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])


# V. Other Basic Ops

## Mean

In [4]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [5]:
# Can't use mean() on integers
t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


You can also use ```t.mean``` for higher rank tensors to get mean of all elements, or mean by particular dimension.

In [6]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [10]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


## Sum

In [11]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [12]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


## Max and Argmax
Argmax is about index value.

In [13]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


The ```max``` operator returns one value if it is called without an argument.

In [14]:
print(t.max()) # Returns one value: max

tensor(4.)


The ```max``` operator *returns 2 values when called with dimension specified*. The first value is the maximum value, and the second value is the argumax: the index of the element with maximum value.

In [15]:
print(t.max(dim=0)) # Returns two values: max and argmax
print('Max: ', t.max(dim=0)[0])
print('Argmax :', t.max(dim=0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax : tensor([1, 1])


In [16]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


## View(Reshape)
Use of view function is important.

In [18]:
t = np.array([[[0, 1, 2],
              [3, 4, 5]],
            
            [[6, 7, 8],
             [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


**|ft|** = (2, 2, 3) # 2 x 2 x 3 = 12 </br>

=> (2x2, 3) = (4, 3) # 2 x 2 x 3 = 12 </br>

=> (2x2, 1, 3) = (4, 1, 3) # 2 x 2 x 3 = 12

In [19]:
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [20]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


Reshape is performed according to values that are not -1.

## Squeeze

In [24]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([0., 1., 2.])
torch.Size([3])


|ft| = (3, 1)
=> (3, )

- ft.squeeze(dim=0): nothing happens because dim=0 is 3.
- ft.squeeze(dim=1): something happens because dim=1 is 0.

When using squeeze(dim=?), it squeeze tensor when there is 1 in that dimension.

## Unsqueeze
Negative of squeeze. Push 1 into the dimension which user wants.

In [27]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [28]:
# push 1 into dim = 0
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [29]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [32]:
# push 1 into dim = 1
# the number of element doesn't changes.
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [31]:
# push 1 into dim = -1
# in this tensor, dim = -1 is equal to dim = 1
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


## Type Casting

In [36]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)
print(lt.float())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])


In [38]:
# ByteTensor save bool value.
bt = torch.ByteTensor([True, False, False, True])
print(bt)
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


## Concatenate

In [39]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])
print(torch.cat([x, y], dim = 0))
print(torch.cat([x, y], dim = 1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


|x| = |y| = (2, 2)
- concatenate at dim = 0: Stack two blocks up and down in the direction of dim = 0. </br>
    (4, 2)
- concatenate at dim = 1: Stack two blocks left and right in the direction of dim = 1. </br>
    (2, 4)

## Stacking

In [43]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])
print(torch.stack([x, y, z])) # (3, 2)
print(torch.stack([x, y, z], dim = 1)) # (2, 3)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [44]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim = 0)) # (3, 2)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


## Ones and Zeros
Help to store tensor at same storage. </br>

When each tensor stores at another device, it makes error. (for example, GPU Tensor + CPU tensor.. or GPU1 Tensor + GPU2 Tensor. They all make error)

In [45]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [46]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## In-Place Operation
Pytorch are good at garbage collection process, you may not have big performance improvement.

In [47]:
x = torch.FloatTensor([[1, 2], [3, 4]])
print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
