# Chapter 01. Tensor Manipulation

- Vector, Matrix and Tensor
- NumPy Review
- PyTorch Tensor Allocation
- Matrix Multiplication
- Other Basic Ops

---------------------

## I. Vector, Matix and Tensor

Vector: 1D </br>
Matrix: 2D </br>
Tensor: 3D

### PyTorch Tensor Shape Convention

The shape operation is important.

#### 2D Tensor (Typical Simple Setting)
- |t| = (batch size, dim)
#### 3D Tensor (Typical Computer Vision)
- |t| = (batch size, width, height)
#### 3D Tensor (Typical Natural Language Processing - NLP)
- |t| = (batch size, length, dim)

---------------------------

# II. NumPy Review

In [4]:
import numpy as np
import torch

## 1D Array with NumPy

In [5]:
t = np.array([0., 1., 2., 3., 4., 5., 6.,])
print(t)
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # Element
print('t[2:5], t[4:-1] = ', t[2:5], t[4:-1]) # Slicing
print('t[:2] t[3:] = ', t[:2], t[3:]) # Slicing

[0. 1. 2. 3. 4. 5. 6.]
Rank of t:  1
Shape of t:  (7,)
t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5], t[4:-1] =  [2. 3. 4.] [4. 5.]
t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


In [6]:
## 2D Array with Numpy

In [7]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [1., 11., 12.]])
print(t)
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [ 1. 11. 12.]]
Rank of t:  2
Shape of t:  (4, 3)


------------

# III. PyTorch Tensor

## 1D Array with PyTorch

In [8]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)
print(t.dim()) # rank
print(t.shape) # shape
print(t.size()) # shape
print(t[0], t[1], t[-1]) # Element
print(t[2:5], t[4:-1]) # Slicing
print(t[:2], t[3:]) # Slicing

tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


## 2D Array with PyTorch

In [12]:
t = torch.FloatTensor([[1., 2., 3.], 
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)
print(t.dim()) # rank
print(t.shape) # shape
print(t.size()) # shape
print(t[:, 1]) # get all row (:) and only second column (1)
print(t[:, 1].size()) # .size() -> get vector value
print(t[:, :-1]) # get all values except the latest coulmn

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
2
torch.Size([4, 3])
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


#### cf) about [:, :] in python
https://stackoverflow.com/questions/57872755/what-is-1-in-python
    
- [:, :]: liberally means [all rows, all coulmns]
- [:, -1]: taking all the rows and only the last column.
- [:, 1]: taking all rows but keeping the second column(1).

## Broadcasting
Automatically adjusts the size when the size of tensor is different.

</br> Because Broadcasting automatic process, finding an error is difficult. So it requires attention.

In [16]:
# Same Shape

m1 = torch.FloatTensor([[3, 3]]) # |m1| = (1, 2)
m2 = torch.FloatTensor([[2, 2]]) # |m1| == |m2|
print(m1 + m2)

tensor([[5., 5.]])


In [17]:
# Vector + Scalar
# Automatic Broadcasting

m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # 3 (scalar) -> [[3, 3]] (vector)
print(m1 + m2)

# |m1| = (1, 2)
# |m2| = (1, ) => (1, 2)
# m1 + m2 = [[1, 2] + [3, 3]]

tensor([[4., 5.]])


In [18]:
# 2 x 1 Vector + 1 x 2 Vector
# Automatic Broadcasting

m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

# |m1| = (1, 2) => (2, 2)
# |m2| = (2, 1) = > (2, 2)
# m1 + m2 = [[1, 2], [1, 2]] + [[3, 3], [4, 4]]

tensor([[4., 5.],
        [5., 6.]])


# IV. Matrix Multiplication

## Multiplication vs Matrix Multiplication
An understanding of matrix multiplication is required.

In [21]:
print('-------')
print('Mul vs Matmul')
print('-------')
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape)
print(m1.matmul(m2))

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape)
print(m1.mul(m2))

-------
Mul vs Matmul
-------
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
