In [1]:
import numpy as np

a = np.random.randn(5)

In [2]:
print(a)

[-0.4092916  -0.4168144   0.30903535  0.11729999  1.32594015]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[-0.4092916  -0.4168144   0.30903535  0.11729999  1.32594015]


In [5]:
print(np.dot(a, a.T))

2.208633281354735


np.random.randn(1, 5) 
→ a.shape = (1, 5) *Row Vector*

In [11]:
a = np.random.randn(1, 5)

print(a)

[[-1.62844931  0.676116   -0.66697405 -0.49834746  1.62227211]]


In [12]:
print(a.T)

[[-1.62844931]
 [ 0.676116  ]
 [-0.66697405]
 [-0.49834746]
 [ 1.62227211]]


In [13]:
print(np.dot(a, a.T))

[[6.43395139]]


np.random.randn(5, 1) → a.shape = (5, 1) *Column Vector*

In [6]:
a = np.random.randn(5, 1)
print(a)

[[-1.77550572]
 [-0.12762606]
 [ 0.81889886]
 [ 0.07998727]
 [ 0.30860801]]


In [7]:
print(a.T)

[[-1.77550572 -0.12762606  0.81889886  0.07998727  0.30860801]]


In [8]:
print(np.dot(a, a.T))

[[ 3.15242056  0.22660081 -1.45395961 -0.14201785 -0.54793529]
 [ 0.22660081  0.01628841 -0.10451284 -0.01020846 -0.03938643]
 [-1.45395961 -0.10451284  0.67059534  0.06550148  0.25271875]
 [-0.14201785 -0.01020846  0.06550148  0.00639796  0.02468471]
 [-0.54793529 -0.03938643  0.25271875  0.02468471  0.0952389 ]]
